name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git perl meson ninja wayland-protocols \
            cairo libevdev libinput pixman libxcb libxkbcommon linux-api-headers \
            pango shaderc vulkan-headers xcb-util-wm xorg-xwayland libliftoff \
            lcms2 xcb-util-errors xcb-util-renderutil seatd vulkan-icd-loader \
            libdisplay-info

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Install wlroots
        run: |
          git clone --depth 1 https://aur.archlinux.org/wlroots-git.git
          cd wlroots-git
          chown -R builder:builder .
          sudo -u builder makepkg -si --noconfirm

      - name: Build
        run: |
          cd arch/
          chown -R builder:builder .
          sudo -u builder makepkg -s --noconfirm
